package shootingGame.Injectors;

import java.awt.*;

interface ButtonsValues {
    Color BACKGROUND_NO_ACTION_COLOR = new Color(0, 0 ,0);
    Color BACKGROUND_MOUSE_ENTERED_COLOR = new Color(51, 51 ,51);
    Color FOREGROUND_COLOR = new Color(255, 255, 255);
    Font FONT = new Font("Italic", Font.BOLD, 20);
    int MENU_BUTTON_WIDTH = 300;
    int MENU_BUTTON_HEIGHT = 100;
    int MENU_BUTTON_X_POSITION = 100;
    int START_BUTTON_Y_POSITION = 150;
    int STATISTICS_BUTTON_Y_POSITION = 300;
    int CLOSE_BUTTON_Y_POSITION = 450;
    int MESSAGE_BUTTON_WIDTH = 200;
    int MESSAGE_BUTTON_HEIGHT = 70;
    int MESSAGE_BUTTON_Y_POSITION = 200;
    int RETURN_TO_GAME_BUTTON_X_POSITION = 275;
    int RETURN_TO_MENU_BUTTON_X_POSITION = 25;
    int OK_BUTTON_X_POSITION = 150;
    int GO_TO_MENU_FROM_STATISTICS_BUTTON_WIDTH = 200;
    int GO_TO_MENU_FROM_STATISTICS_BUTTON_HEIGHT = 75;
    int GO_TO_MENU_FROM_STATISTICS_BUTTON_X_POSITION = 25;
    int GO_TO_MENU_FROM_STATISTICS_BUTTON_Y_POSITION = 25;
}
